networks:
  proxy:
    driver: bridge
    name: vbrowser_proxy
    ipam:
      config:
        - subnet: 172.20.0.0/24


services:

  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard_home
    ports:
      - "3000:3000/tcp"
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./adguard/conf:/opt/adguardhome/conf
      - ./adguard/work:/opt/adguardhome/work
    restart: unless-stopped
    networks:
      proxy:
        ipv4_address: 172.20.0.2


  traefik:
    image: traefik:2.11
    container_name: vbrowser-traefik
    restart: unless-stopped
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=vbrowser_proxy
      - --entrypoints.web.address=:80
      - --providers.file.directory=/etc/traefik/dynamic
    ports:
      - "80:80"
      - "8888:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik-dynamic.yml:/etc/traefik/dynamic/dynamic.yml:ro
    networks:
      - proxy


  backend:
    build: .
    container_name: vbrowser-backend
    restart: unless-stopped
    env_file:
      - .env
    dns:
      - 172.20.0.2
    volumes:
      - ./backend.py:/app/backend.py
      - ./main.py:/app/main.py
      - ./frontend.py:/app/frontend.py
      - ./database.py:/app/database.py
      - ./routes:/app/routes
      - ./.data:/appdata
      - /var/run/docker.sock:/var/run/docker.sock
      # Seccomp-Profil (nur benoetigt wenn BROWSER_SECCOMP_MODE=profile)
      - /opt/vbrowser/seccomp_profile.json:/opt/vbrowser/seccomp_profile.json:ro
    networks:
      - proxy
    depends_on:
      - adguard
    labels:
      - traefik.enable=true
      - traefik.http.routers.vbrowser-backend.rule=Host(`vbrowser.de`)
      - traefik.http.routers.vbrowser-backend.entrypoints=web
      - traefik.http.services.vbrowser-backend.loadbalancer.server.port=8080
      - traefik.http.routers.vbrowser-auth.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.vbrowser.de`) && Path(`/auth/set-cookie`)
      - traefik.http.routers.vbrowser-auth.entrypoints=web
      - traefik.http.routers.vbrowser-auth.service=vbrowser-backend
      - traefik.http.routers.vbrowser-auth.priority=10
      - "traefik.http.middlewares.vbrowser-auth.forwardauth.address=http://vbrowser-backend:8080/auth/verify"
      - "traefik.http.middlewares.vbrowser-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.vbrowser-auth.forwardauth.authResponseHeaders=X-Forwarded-User"


  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - proxy
    depends_on:
      - adguard
